import {
  Property,
  Booking,
  AIAction,
  MonthlyRevenue,
  Deposit,
  ExtraCharge,
  PricingRecommendation,
  PayoutSummary,
  GuestConversation,
  PropertySetupResult,
} from "./types";

// ============================================================
// OPENCLAW_HOOK: Live property data
// Integration: GET ${NEXT_PUBLIC_OPENCLAW_URL}/properties
// Current behavior: Returns hard-coded property list
// ============================================================
export const properties: Property[] = [
  {
    id: "prop-1",
    name: "Waikiki Beachfront Condo",
    type: "beachfront-condo",
    location: { lat: 21.2766, lng: -157.8272 },
    address: "2161 Kalia Rd, Honolulu, HI 96815",
    rate: 320,
    color: "#3B82F6",
    occupancy: 92,
    nextBooking: "2026-03-16",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=640&h=360&fit=crop&auto=format",
  },
  {
    id: "prop-2",
    name: "Diamond Head Ocean Suite",
    type: "beachfront-condo",
    location: { lat: 21.2614, lng: -157.8078 },
    address: "3045 Monsarrat Ave, Honolulu, HI 96815",
    rate: 285,
    color: "#8B5CF6",
    occupancy: 88,
    nextBooking: "2026-03-18",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=640&h=360&fit=crop&auto=format",
  },
  {
    id: "prop-3",
    name: "Kailua Beach House",
    type: "house",
    location: { lat: 21.3969, lng: -157.726 },
    address: "438 Kawailoa Rd, Kailua, HI 96734",
    rate: 450,
    color: "#10B981",
    occupancy: 78,
    nextBooking: "2026-03-20",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=640&h=360&fit=crop&auto=format",
  },
  {
    id: "prop-4",
    name: "Waikiki Studio Retreat",
    type: "studio",
    location: { lat: 21.2819, lng: -157.8311 },
    address: "2330 Kuhio Ave, Honolulu, HI 96815",
    rate: 175,
    color: "#F59E0B",
    occupancy: 95,
    nextBooking: "2026-03-15",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=640&h=360&fit=crop&auto=format",
  },
  {
    id: "prop-5",
    name: "Manoa Valley Townhouse",
    type: "townhouse",
    location: { lat: 21.3156, lng: -157.8042 },
    address: "3142 Manoa Rd, Honolulu, HI 96822",
    rate: 225,
    color: "#EF4444",
    occupancy: 82,
    nextBooking: "2026-03-22",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=640&h=360&fit=crop&auto=format",
  },
];

// ============================================================
// OPENCLAW_HOOK: Live booking data
// Integration: GET ${NEXT_PUBLIC_OPENCLAW_URL}/bookings
// Current behavior: Returns hard-coded booking list
// ============================================================
export const bookings: Booking[] = [
  {
    id: "bk-1",
    propertyId: "prop-1",
    guestName: "Sarah Chen",
    guestEmail: "sarah.chen@email.com",
    guestPhone: "+1 (808) 555-0142",
    guestAvatar: "https://i.pravatar.cc/64?img=47",
    checkIn: "2026-03-10",
    checkOut: "2026-03-15",
    nightlyRate: 320,
    totalAmount: 1600,
    source: "airbnb",
    status: "checked-in",
    guests: 2,
  },
  {
    id: "bk-2",
    propertyId: "prop-1",
    guestName: "Michael Torres",
    guestEmail: "m.torres@email.com",
    checkIn: "2026-03-16",
    checkOut: "2026-03-21",
    nightlyRate: 340,
    totalAmount: 1700,
    source: "vrbo",
    status: "confirmed",
    guests: 3,
  },
  {
    id: "bk-3",
    propertyId: "prop-2",
    guestName: "Emily Watson",
    guestEmail: "emily.w@email.com",
    guestPhone: "+1 (415) 555-0289",
    guestAvatar: "https://i.pravatar.cc/64?img=5",
    checkIn: "2026-03-08",
    checkOut: "2026-03-14",
    nightlyRate: 285,
    totalAmount: 1710,
    source: "airbnb",
    status: "checked-in",
    guests: 2,
  },
  {
    id: "bk-4",
    propertyId: "prop-2",
    guestName: "James Park",
    guestEmail: "j.park@email.com",
    checkIn: "2026-03-18",
    checkOut: "2026-03-24",
    nightlyRate: 300,
    totalAmount: 1800,
    source: "direct",
    status: "confirmed",
    guests: 4,
  },
  {
    id: "bk-5",
    propertyId: "prop-3",
    guestName: "Lisa Nakamura",
    guestEmail: "lisa.n@email.com",
    checkIn: "2026-03-05",
    checkOut: "2026-03-12",
    nightlyRate: 450,
    totalAmount: 3150,
    source: "airbnb",
    status: "completed",
    guests: 6,
  },
  {
    id: "bk-6",
    propertyId: "prop-3",
    guestName: "Robert Kim",
    guestEmail: "r.kim@email.com",
    checkIn: "2026-03-20",
    checkOut: "2026-03-27",
    nightlyRate: 475,
    totalAmount: 3325,
    source: "vrbo",
    status: "confirmed",
    guests: 5,
  },
  {
    id: "bk-7",
    propertyId: "prop-4",
    guestName: "Amanda Liu",
    guestEmail: "a.liu@email.com",
    guestPhone: "+1 (213) 555-0374",
    guestAvatar: "https://i.pravatar.cc/64?img=9",
    checkIn: "2026-03-12",
    checkOut: "2026-03-16",
    nightlyRate: 175,
    totalAmount: 700,
    source: "airbnb",
    status: "checked-in",
    guests: 1,
  },
  {
    id: "bk-8",
    propertyId: "prop-4",
    guestName: "David Brown",
    guestEmail: "d.brown@email.com",
    checkIn: "2026-03-17",
    checkOut: "2026-03-20",
    nightlyRate: 185,
    totalAmount: 555,
    source: "direct",
    status: "confirmed",
    guests: 2,
  },
  {
    id: "bk-9",
    propertyId: "prop-5",
    guestName: "Jennifer Huang",
    guestEmail: "j.huang@email.com",
    checkIn: "2026-03-09",
    checkOut: "2026-03-13",
    nightlyRate: 225,
    totalAmount: 900,
    source: "vrbo",
    status: "completed",
    guests: 3,
  },
  {
    id: "bk-10",
    propertyId: "prop-5",
    guestName: "Chris Martinez",
    guestEmail: "c.martinez@email.com",
    guestPhone: "+1 (310) 555-0517",
    guestAvatar: "https://i.pravatar.cc/64?img=12",
    checkIn: "2026-03-14",
    checkOut: "2026-03-18",
    nightlyRate: 225,
    totalAmount: 900,
    source: "airbnb",
    status: "checked-in",
    guests: 2,
  },
  {
    id: "bk-11",
    propertyId: "prop-1",
    guestName: "Anna Schmidt",
    guestEmail: "a.schmidt@email.com",
    checkIn: "2026-03-24",
    checkOut: "2026-03-29",
    nightlyRate: 350,
    totalAmount: 1750,
    source: "airbnb",
    status: "confirmed",
    guests: 2,
  },
  {
    id: "bk-12",
    propertyId: "prop-2",
    guestName: "Tom Wilson",
    guestEmail: "t.wilson@email.com",
    checkIn: "2026-02-25",
    checkOut: "2026-03-02",
    nightlyRate: 285,
    totalAmount: 1425,
    source: "vrbo",
    status: "completed",
    guests: 2,
  },
  {
    id: "bk-13",
    propertyId: "prop-3",
    guestName: "Kate Johnson",
    guestEmail: "k.johnson@email.com",
    checkIn: "2026-02-20",
    checkOut: "2026-02-28",
    nightlyRate: 430,
    totalAmount: 3440,
    source: "direct",
    status: "completed",
    guests: 4,
  },
  {
    id: "bk-14",
    propertyId: "prop-4",
    guestName: "Ryan Patel",
    guestEmail: "r.patel@email.com",
    checkIn: "2026-03-22",
    checkOut: "2026-03-26",
    nightlyRate: 190,
    totalAmount: 760,
    source: "airbnb",
    status: "confirmed",
    guests: 2,
  },
  {
    id: "bk-15",
    propertyId: "prop-5",
    guestName: "Maria Garcia",
    guestEmail: "m.garcia@email.com",
    checkIn: "2026-03-22",
    checkOut: "2026-03-28",
    nightlyRate: 240,
    totalAmount: 1440,
    source: "vrbo",
    status: "confirmed",
    guests: 3,
  },
  {
    id: "bk-16",
    propertyId: "prop-1",
    guestName: "Kevin Tanaka",
    guestEmail: "k.tanaka@email.com",
    checkIn: "2026-02-15",
    checkOut: "2026-02-20",
    nightlyRate: 310,
    totalAmount: 1550,
    source: "airbnb",
    status: "completed",
    guests: 2,
  },
  {
    id: "bk-17",
    propertyId: "prop-4",
    guestName: "Sophie Lee",
    guestEmail: "s.lee@email.com",
    checkIn: "2026-03-02",
    checkOut: "2026-03-07",
    nightlyRate: 175,
    totalAmount: 875,
    source: "vrbo",
    status: "completed",
    guests: 1,
  },
  // Early February bookings
  {
    id: "bk-18",
    propertyId: "prop-1",
    guestName: "Nathan Brooks",
    guestEmail: "n.brooks@email.com",
    checkIn: "2026-02-01",
    checkOut: "2026-02-05",
    nightlyRate: 320,
    totalAmount: 1280,
    source: "airbnb",
    status: "completed",
    guests: 2,
  },
  {
    id: "bk-19",
    propertyId: "prop-2",
    guestName: "Priya Sharma",
    guestEmail: "p.sharma@email.com",
    checkIn: "2026-02-02",
    checkOut: "2026-02-07",
    nightlyRate: 285,
    totalAmount: 1425,
    source: "vrbo",
    status: "completed",
    guests: 3,
  },
  {
    id: "bk-20",
    propertyId: "prop-3",
    guestName: "Daniel Reeves",
    guestEmail: "d.reeves@email.com",
    checkIn: "2026-02-03",
    checkOut: "2026-02-08",
    nightlyRate: 450,
    totalAmount: 2250,
    source: "direct",
    status: "completed",
    guests: 5,
  },
  {
    id: "bk-21",
    propertyId: "prop-4",
    guestName: "Olivia Grant",
    guestEmail: "o.grant@email.com",
    checkIn: "2026-02-04",
    checkOut: "2026-02-07",
    nightlyRate: 175,
    totalAmount: 525,
    source: "airbnb",
    status: "completed",
    guests: 1,
  },
  {
    id: "bk-22",
    propertyId: "prop-5",
    guestName: "Marcus Reed",
    guestEmail: "m.reed@email.com",
    checkIn: "2026-02-05",
    checkOut: "2026-02-09",
    nightlyRate: 225,
    totalAmount: 900,
    source: "vrbo",
    status: "completed",
    guests: 2,
  },
  // Mid February bookings
  {
    id: "bk-23",
    propertyId: "prop-1",
    guestName: "Claire Nguyen",
    guestEmail: "c.nguyen@email.com",
    checkIn: "2026-02-08",
    checkOut: "2026-02-12",
    nightlyRate: 310,
    totalAmount: 1240,
    source: "airbnb",
    status: "completed",
    guests: 2,
  },
  {
    id: "bk-24",
    propertyId: "prop-2",
    guestName: "Leo Fitzgerald",
    guestEmail: "l.fitz@email.com",
    checkIn: "2026-02-10",
    checkOut: "2026-02-15",
    nightlyRate: 285,
    totalAmount: 1425,
    source: "airbnb",
    status: "completed",
    guests: 2,
  },
  {
    id: "bk-25",
    propertyId: "prop-3",
    guestName: "Yuki Tanaka",
    guestEmail: "y.tanaka@email.com",
    checkIn: "2026-02-12",
    checkOut: "2026-02-17",
    nightlyRate: 450,
    totalAmount: 2250,
    source: "vrbo",
    status: "completed",
    guests: 4,
  },
  {
    id: "bk-26",
    propertyId: "prop-5",
    guestName: "Ethan Cole",
    guestEmail: "e.cole@email.com",
    checkIn: "2026-02-16",
    checkOut: "2026-02-19",
    nightlyRate: 225,
    totalAmount: 675,
    source: "direct",
    status: "completed",
    guests: 2,
  },
  // Late February bookings
  {
    id: "bk-27",
    propertyId: "prop-4",
    guestName: "Hannah Mills",
    guestEmail: "h.mills@email.com",
    checkIn: "2026-02-22",
    checkOut: "2026-02-26",
    nightlyRate: 175,
    totalAmount: 700,
    source: "airbnb",
    status: "completed",
    guests: 1,
  },
  {
    id: "bk-28",
    propertyId: "prop-1",
    guestName: "Jacob Flynn",
    guestEmail: "j.flynn@email.com",
    checkIn: "2026-02-24",
    checkOut: "2026-02-28",
    nightlyRate: 320,
    totalAmount: 1280,
    source: "vrbo",
    status: "completed",
    guests: 3,
  },
  // Early March bookings
  {
    id: "bk-29",
    propertyId: "prop-2",
    guestName: "Sophia Durant",
    guestEmail: "s.durant@email.com",
    checkIn: "2026-03-03",
    checkOut: "2026-03-08",
    nightlyRate: 285,
    totalAmount: 1425,
    source: "direct",
    status: "completed",
    guests: 2,
  },
  {
    id: "bk-30",
    propertyId: "prop-5",
    guestName: "Aiden Park",
    guestEmail: "a.park@email.com",
    checkIn: "2026-03-04",
    checkOut: "2026-03-08",
    nightlyRate: 225,
    totalAmount: 900,
    source: "airbnb",
    status: "completed",
    guests: 2,
  },
];

// ============================================================
// OPENCLAW_HOOK: Real-time AI action feed
// Integration: WebSocket ${NEXT_PUBLIC_OPENCLAW_URL}/ws/actions
// Current behavior: Returns hard-coded action list
// ============================================================
export const aiActions: AIAction[] = [
  {
    id: "act-1",
    propertyId: "prop-1",
    category: "cleaning",
    title: "Scheduled turnover cleaning",
    description:
      "Booked Sparkle Clean Co. for March 15 checkout. Deep clean + linen change.",
    timestamp: "2026-03-14T09:30:00Z",
    status: "completed",
    cost: 185,
  },
  {
    id: "act-2",
    propertyId: "prop-3",
    category: "amazon",
    title: "Restocked kitchen supplies",
    description:
      "Ordered dish soap, sponges, paper towels, and trash bags via Amazon. Delivery by March 13.",
    timestamp: "2026-03-13T22:15:00Z",
    status: "completed",
    cost: 47,
  },
  {
    id: "act-3",
    propertyId: "prop-4",
    category: "pricing",
    title: "Adjusted weekend rate",
    description:
      "Increased nightly rate from $175 to $195 for March 20-22 weekend based on demand surge.",
    timestamp: "2026-03-13T18:00:00Z",
    status: "completed",
  },
  {
    id: "act-4",
    propertyId: "prop-2",
    category: "messaging",
    title: "Sent check-in instructions",
    description:
      "Auto-sent check-in guide with door code, WiFi, and parking info to Emily Watson.",
    timestamp: "2026-03-13T14:00:00Z",
    status: "completed",
  },
  {
    id: "act-5",
    propertyId: "prop-5",
    category: "repair",
    title: "Submitted maintenance request",
    description:
      "Guest reported AC making noise. Contacted Island HVAC for inspection on March 15.",
    timestamp: "2026-03-13T11:30:00Z",
    status: "in-progress",
    cost: 150,
  },
  {
    id: "act-6",
    propertyId: "prop-1",
    category: "calendar",
    title: "Synced Airbnb calendar",
    description:
      "Updated availability on Airbnb and VRBO. Blocked March 15 for cleaning buffer.",
    timestamp: "2026-03-13T08:00:00Z",
    status: "completed",
  },
  {
    id: "act-7",
    propertyId: "prop-3",
    category: "cleaning",
    title: "Mid-stay towel refresh",
    description:
      "Arranged fresh towel delivery for Kailua Beach House. Guest requested extra bath towels.",
    timestamp: "2026-03-12T16:45:00Z",
    status: "completed",
    cost: 45,
  },
  {
    id: "act-8",
    propertyId: "prop-2",
    category: "amazon",
    title: "Ordered replacement pillows",
    description:
      "2x king-size hypoallergenic pillows ordered. Previous set showing wear after 6 months.",
    timestamp: "2026-03-12T10:20:00Z",
    status: "completed",
    cost: 89,
  },
  {
    id: "act-9",
    propertyId: "prop-4",
    category: "messaging",
    title: "Responded to guest inquiry",
    description:
      'Auto-replied to Amanda Liu asking about late checkout. Offered 1pm checkout for $25 fee.',
    timestamp: "2026-03-12T08:15:00Z",
    status: "completed",
  },
  {
    id: "act-10",
    propertyId: "prop-5",
    category: "pricing",
    title: "Lowered midweek rate",
    description:
      "Reduced Tuesday-Thursday rate by 12% to fill gap. Competitor analysis showed lower demand.",
    timestamp: "2026-03-11T20:00:00Z",
    status: "completed",
  },
  {
    id: "act-11",
    propertyId: "prop-1",
    category: "messaging",
    title: "Sent checkout reminder",
    description:
      "Reminded Sarah Chen about March 15 checkout. Included trash/linens instructions.",
    timestamp: "2026-03-11T17:00:00Z",
    status: "completed",
  },
  {
    id: "act-12",
    propertyId: "prop-3",
    category: "repair",
    title: "Fixed leaking faucet",
    description:
      "Plumber completed kitchen faucet repair at Kailua Beach House. Washer replacement.",
    timestamp: "2026-03-10T14:30:00Z",
    status: "completed",
    cost: 120,
  },
  {
    id: "act-13",
    propertyId: "prop-2",
    category: "calendar",
    title: "Blocked dates for maintenance",
    description:
      "Reserved March 25-26 for deep cleaning and AC filter replacement at Diamond Head Suite.",
    timestamp: "2026-03-10T09:00:00Z",
    status: "pending",
  },
  {
    id: "act-14",
    propertyId: "prop-4",
    category: "cleaning",
    title: "Emergency spot clean",
    description:
      "Guest reported coffee spill on carpet. Arranged same-day spot cleaning service.",
    timestamp: "2026-03-09T19:00:00Z",
    status: "completed",
    cost: 75,
  },
  {
    id: "act-15",
    propertyId: "prop-5",
    category: "amazon",
    title: "Restocked bathroom amenities",
    description:
      "Ordered shampoo, conditioner, body wash, and hand soap refills for Manoa Townhouse.",
    timestamp: "2026-03-08T11:00:00Z",
    status: "completed",
    cost: 62,
  },
];

// ============================================================
// OPENCLAW_HOOK: Revenue analytics
// Integration: GET ${NEXT_PUBLIC_OPENCLAW_URL}/analytics/revenue
// Current behavior: Returns hard-coded monthly revenue data
// ============================================================
export const monthlyRevenue: MonthlyRevenue[] = [
  { month: "Apr 2025", revenue: 18200, expenses: 4800 },
  { month: "May 2025", revenue: 21500, expenses: 5200 },
  { month: "Jun 2025", revenue: 26800, expenses: 5900 },
  { month: "Jul 2025", revenue: 31200, expenses: 6800 },
  { month: "Aug 2025", revenue: 29400, expenses: 6200 },
  { month: "Sep 2025", revenue: 22100, expenses: 5100 },
  { month: "Oct 2025", revenue: 19800, expenses: 4600 },
  { month: "Nov 2025", revenue: 23500, expenses: 5400 },
  { month: "Dec 2025", revenue: 32100, expenses: 7200 },
  { month: "Jan 2026", revenue: 27300, expenses: 6100 },
  { month: "Feb 2026", revenue: 25800, expenses: 5700 },
  { month: "Mar 2026", revenue: 28450, expenses: 6300 },
];

// ============================================================
// OPENCLAW_HOOK: Deposit tracking
// Integration: GET ${NEXT_PUBLIC_OPENCLAW_URL}/finances/deposits
// Current behavior: Returns hard-coded deposit list
// ============================================================
export const deposits: Deposit[] = [
  { id: "dep-1", date: "2026-03-14", guestName: "Sarah Chen", propertyId: "prop-1", source: "airbnb", amount: 1600 },
  { id: "dep-2", date: "2026-03-12", guestName: "Emily Watson", propertyId: "prop-2", source: "airbnb", amount: 1710 },
  { id: "dep-3", date: "2026-03-10", guestName: "Lisa Nakamura", propertyId: "prop-3", source: "airbnb", amount: 3150 },
  { id: "dep-4", date: "2026-03-09", guestName: "Jennifer Huang", propertyId: "prop-5", source: "vrbo", amount: 900 },
  { id: "dep-5", date: "2026-03-07", guestName: "Sophie Lee", propertyId: "prop-4", source: "vrbo", amount: 875 },
  { id: "dep-6", date: "2026-03-02", guestName: "Tom Wilson", propertyId: "prop-2", source: "vrbo", amount: 1425 },
  { id: "dep-7", date: "2026-02-28", guestName: "Kate Johnson", propertyId: "prop-3", source: "direct", amount: 3440 },
  { id: "dep-8", date: "2026-02-20", guestName: "Kevin Tanaka", propertyId: "prop-1", source: "airbnb", amount: 1550 },
  { id: "dep-9", date: "2026-03-13", guestName: "Amanda Liu", propertyId: "prop-4", source: "airbnb", amount: 700 },
  { id: "dep-10", date: "2026-03-13", guestName: "Chris Martinez", propertyId: "prop-5", source: "airbnb", amount: 900 },
];

// ============================================================
// OPENCLAW_HOOK: Expense tracking
// Integration: GET ${NEXT_PUBLIC_OPENCLAW_URL}/finances/charges
// Current behavior: Returns hard-coded charge list
// ============================================================
export const extraCharges: ExtraCharge[] = [
  { id: "chg-1", date: "2026-03-14", propertyId: "prop-1", category: "Cleaning", description: "Turnover deep clean - Sparkle Clean Co.", amount: 185, aiInitiated: true },
  { id: "chg-2", date: "2026-03-13", propertyId: "prop-3", category: "Supplies", description: "Kitchen supplies restock via Amazon", amount: 47, aiInitiated: true },
  { id: "chg-3", date: "2026-03-13", propertyId: "prop-5", category: "Repair", description: "AC inspection - Island HVAC", amount: 150, aiInitiated: true },
  { id: "chg-4", date: "2026-03-12", propertyId: "prop-3", category: "Cleaning", description: "Mid-stay towel refresh service", amount: 45, aiInitiated: true },
  { id: "chg-5", date: "2026-03-12", propertyId: "prop-2", category: "Supplies", description: "Replacement pillows (2x king)", amount: 89, aiInitiated: true },
  { id: "chg-6", date: "2026-03-10", propertyId: "prop-3", category: "Repair", description: "Kitchen faucet repair - plumber", amount: 120, aiInitiated: false },
  { id: "chg-7", date: "2026-03-09", propertyId: "prop-4", category: "Cleaning", description: "Emergency carpet spot clean", amount: 75, aiInitiated: true },
  { id: "chg-8", date: "2026-03-08", propertyId: "prop-5", category: "Supplies", description: "Bathroom amenity restock", amount: 62, aiInitiated: true },
  // February charges
  { id: "chg-9",  date: "2026-02-03", propertyId: "prop-1", category: "Cleaning",  description: "Turnover clean after early Feb checkout",    amount: 150, aiInitiated: true  },
  { id: "chg-10", date: "2026-02-07", propertyId: "prop-2", category: "Supplies",  description: "Restocked toiletries and coffee supplies",     amount: 80,  aiInitiated: true  },
  { id: "chg-11", date: "2026-02-10", propertyId: "prop-3", category: "Repair",    description: "Replaced broken patio screen door",           amount: 220, aiInitiated: false },
  { id: "chg-12", date: "2026-02-14", propertyId: "prop-4", category: "Cleaning",  description: "Valentine's Day turnover deep clean",          amount: 75,  aiInitiated: true  },
  { id: "chg-13", date: "2026-02-18", propertyId: "prop-5", category: "Supplies",  description: "Restocked kitchen consumables via Amazon",     amount: 58,  aiInitiated: true  },
  { id: "chg-14", date: "2026-02-22", propertyId: "prop-1", category: "Repair",    description: "Fixed loose towel rail in master bath",        amount: 95,  aiInitiated: false },
  { id: "chg-15", date: "2026-02-25", propertyId: "prop-2", category: "Cleaning",  description: "Pre-checkout professional clean",              amount: 165, aiInitiated: true  },
  { id: "chg-16", date: "2026-02-26", propertyId: "prop-3", category: "Supplies",  description: "Ordered new beach towels and pool floats",     amount: 140, aiInitiated: true  },
  { id: "chg-17", date: "2026-03-04", propertyId: "prop-4", category: "Repair",    description: "Dishwasher drainage unclogged",                amount: 110, aiInitiated: false },
  { id: "chg-18", date: "2026-03-06", propertyId: "prop-1", category: "Supplies",  description: "Restocked welcome basket items",               amount: 45,  aiInitiated: true  },
];

// ============================================================
// OPENCLAW_HOOK: AI pricing recommendations
// Integration: GET ${NEXT_PUBLIC_OPENCLAW_URL}/pricing/recommendations
// Current behavior: Returns hard-coded recommendations
// ============================================================
export const pricingRecommendations: PricingRecommendation[] = [
  {
    id: "rec-1",
    propertyId: "prop-1",
    currentRate: 320,
    suggestedRate: 380,
    reason: "Spring break demand surge detected. Competitor rates up 15-20% for beachfront units.",
    dateRange: { start: "2026-03-28", end: "2026-04-05" },
    status: "pending",
  },
  {
    id: "rec-2",
    propertyId: "prop-3",
    currentRate: 450,
    suggestedRate: 520,
    reason: "Easter weekend premium. Kailua Beach House historically books at 95%+ during holidays.",
    dateRange: { start: "2026-04-03", end: "2026-04-06" },
    status: "pending",
  },
  {
    id: "rec-3",
    propertyId: "prop-5",
    currentRate: 225,
    suggestedRate: 195,
    reason: "Low demand week detected. Reducing rate to improve fill rate and avoid vacancy.",
    dateRange: { start: "2026-04-07", end: "2026-04-11" },
    status: "pending",
  },
];

// ============================================================
// OPENCLAW_HOOK: Financial summary
// Integration: GET ${NEXT_PUBLIC_OPENCLAW_URL}/finances/summary
// Current behavior: Returns hard-coded payout summary
// ============================================================
export const payoutSummary: PayoutSummary = {
  totalRevenue: 28450,
  totalExpenses: 6300,
  netIncome: 22150,
};

// ============================================================
// OPENCLAW_HOOK: AI agent conversation logs
// Integration: GET ${NEXT_PUBLIC_OPENCLAW_URL}/conversations
// Current behavior: Returns hard-coded conversation data
// ============================================================
export const guestConversations: GuestConversation[] = [
  {
    id: "conv-1",
    bookingId: "bk-1",
    guestName: "Sarah Chen",
    guestAvatar: "https://i.pravatar.cc/64?img=47",
    propertyId: "prop-1",
    lastMessageTime: "2026-03-14T10:22:00Z",
    unreadCount: 0,
    messages: [
      { id: "m1-1", role: "guest", content: "Hi! We're so excited for our stay. Any chance of early check-in around 11am?", timestamp: "2026-03-09T14:30:00Z" },
      { id: "m1-2", role: "agent", content: "Hi Sarah! Welcome 🌺 Standard check-in is 3pm, but let me check if the previous guest checked out early—I'll confirm by tomorrow morning!", timestamp: "2026-03-09T14:31:00Z" },
      { id: "m1-3", role: "agent", content: "Great news! The previous guest checked out yesterday, so early check-in at 11am is all yours.", timestamp: "2026-03-10T08:15:00Z" },
      { id: "m1-4", role: "guest", content: "That's amazing, thank you so much! Quick question—is there parking available?", timestamp: "2026-03-10T09:02:00Z" },
      { id: "m1-5", role: "agent", content: "Yes! You have reserved Spot B-12 in the underground garage. Access card is in the lockbox with your key. Street parking is also free after 6pm if you need a second spot.", timestamp: "2026-03-10T09:03:00Z" },
      { id: "m1-6", role: "guest", content: "Just checked in—the view is absolutely stunning 😍 Thank you!", timestamp: "2026-03-10T11:45:00Z" },
      { id: "m1-7", role: "agent", content: "So glad you love it! Enjoy your stay. Checkout is March 15th by 11am. Don't hesitate to reach out if you need anything!", timestamp: "2026-03-10T11:46:00Z" },
      { id: "m1-8", role: "guest", content: "One quick thing—what's the WiFi password again?", timestamp: "2026-03-14T10:20:00Z" },
      { id: "m1-9", role: "agent", content: "Network: WaikikiBeachfront | Password: Paradise2026# — it's also on the card on the kitchen counter!", timestamp: "2026-03-14T10:22:00Z" },
    ],
  },
  {
    id: "conv-2",
    bookingId: "bk-3",
    guestName: "Emily Watson",
    guestAvatar: "https://i.pravatar.cc/64?img=5",
    propertyId: "prop-2",
    lastMessageTime: "2026-03-11T16:05:00Z",
    unreadCount: 1,
    messages: [
      { id: "m2-1", role: "agent", content: "Hi Emily! Your check-in at Diamond Head Ocean Suite is confirmed for March 8th at 3pm. Door code: 4891. WiFi: DiamondHead_Guest / PW: OceanView!23", timestamp: "2026-03-07T09:00:00Z" },
      { id: "m2-2", role: "guest", content: "Thanks! We arrived safely. Beautiful place! One issue though—the AC is making a rattling noise.", timestamp: "2026-03-08T18:30:00Z" },
      { id: "m2-3", role: "agent", content: "I'm sorry about that! I've already submitted a maintenance request to Island HVAC. A technician will come by tomorrow between 10am–12pm to inspect. Does that work for you?", timestamp: "2026-03-08T18:31:00Z" },
      { id: "m2-4", role: "guest", content: "That works perfectly, thank you for the quick response!", timestamp: "2026-03-08T18:45:00Z" },
      { id: "m2-5", role: "agent", content: "The technician confirmed the repair is complete—just a loose fan bracket. Everything should be quiet now!", timestamp: "2026-03-09T12:30:00Z" },
      { id: "m2-6", role: "guest", content: "Yes, much quieter! Loving the ocean view from the lanai every morning ☀️", timestamp: "2026-03-09T19:00:00Z" },
      { id: "m2-7", role: "agent", content: "Wonderful! Checkout is March 14th by 11am. Please leave keys in the lockbox. Safe travels!", timestamp: "2026-03-13T09:00:00Z" },
      { id: "m2-8", role: "guest", content: "We'll be so sad to leave! Any chance of a 1pm checkout?", timestamp: "2026-03-11T16:04:00Z" },
      { id: "m2-9", role: "agent", content: "I checked the schedule—cleaning crew arrives at noon. I can offer 12pm checkout at no charge as a courtesy. Would that work?", timestamp: "2026-03-11T16:05:00Z" },
    ],
  },
  {
    id: "conv-3",
    bookingId: "bk-7",
    guestName: "Amanda Liu",
    guestAvatar: "https://i.pravatar.cc/64?img=9",
    propertyId: "prop-4",
    lastMessageTime: "2026-03-13T08:30:00Z",
    unreadCount: 2,
    messages: [
      { id: "m3-1", role: "guest", content: "Hello! I'm arriving late—around 9pm. Is that okay?", timestamp: "2026-03-12T07:15:00Z" },
      { id: "m3-2", role: "agent", content: "Absolutely! Lockbox is to the right of the front door, code 7743. You can check in anytime—the studio will be all ready for you.", timestamp: "2026-03-12T07:16:00Z" },
      { id: "m3-3", role: "guest", content: "Just arrived! So cozy and I love the Waikiki location 🌺", timestamp: "2026-03-12T21:30:00Z" },
      { id: "m3-4", role: "agent", content: "Welcome! The beach is a 3-min walk. Surfboard rentals are at the stand by the Outrigger hotel if you're interested. Enjoy your stay!", timestamp: "2026-03-12T21:31:00Z" },
      { id: "m3-5", role: "guest", content: "Oh no—I spilled coffee on the carpet this morning. I'm so sorry!", timestamp: "2026-03-13T08:20:00Z" },
      { id: "m3-6", role: "agent", content: "No worries at all! I've arranged a spot cleaning service for today at 2pm. You don't need to be present and there's no charge to you.", timestamp: "2026-03-13T08:22:00Z" },
      { id: "m3-7", role: "guest", content: "Thank you, that's incredibly kind! One more thing—is it possible to get late checkout at 1pm on the 16th?", timestamp: "2026-03-13T08:28:00Z" },
      { id: "m3-8", role: "agent", content: "I can offer 1pm checkout for a $25 late checkout fee. Would you like to confirm?", timestamp: "2026-03-13T08:30:00Z" },
    ],
  },
  {
    id: "conv-4",
    bookingId: "bk-10",
    guestName: "Chris Martinez",
    guestAvatar: "https://i.pravatar.cc/64?img=12",
    propertyId: "prop-5",
    lastMessageTime: "2026-03-15T11:00:00Z",
    unreadCount: 0,
    messages: [
      { id: "m4-1", role: "agent", content: "Hi Chris! Your booking at Manoa Valley Townhouse is confirmed for March 14th at 3pm. Lockbox code: 2251. Let me know if you have questions!", timestamp: "2026-03-13T10:00:00Z" },
      { id: "m4-2", role: "guest", content: "Thanks! Do you have restaurant recommendations nearby?", timestamp: "2026-03-14T16:00:00Z" },
      { id: "m4-3", role: "agent", content: "Of course! My top picks near Manoa Valley:\n\n🍜 Pai's Restaurant (0.4mi) — local plate lunches\n🥗 Morning Glass Coffee (0.5mi) — best acai bowls in town\n🍕 Da Kitchen (0.8mi) — legendary local comfort food\n🌮 Hank's Haute Dogs (1.2mi) — creative gourmet hot dogs", timestamp: "2026-03-14T16:01:00Z" },
      { id: "m4-4", role: "guest", content: "We went to Morning Glass and it was incredible! Thanks for the tip 🙏", timestamp: "2026-03-15T09:30:00Z" },
      { id: "m4-5", role: "agent", content: "So glad you enjoyed it! Also—Manoa Falls trail is just 10 min away. Short 1.6mi round trip through lush rainforest, totally worth it!", timestamp: "2026-03-15T09:31:00Z" },
      { id: "m4-6", role: "guest", content: "We did the hike this morning! Breathtaking. This neighborhood is so serene compared to Waikiki.", timestamp: "2026-03-15T11:00:00Z" },
    ],
  },
  {
    id: "conv-5",
    bookingId: "bk-2",
    guestName: "Michael Torres",
    guestAvatar: "https://i.pravatar.cc/64?img=33",
    propertyId: "prop-1",
    lastMessageTime: "2026-03-16T15:46:00Z",
    unreadCount: 0,
    messages: [
      { id: "m5-1", role: "guest", content: "Quick question before we arrive—is the building right on the beach or do we need to walk?", timestamp: "2026-03-15T11:00:00Z" },
      { id: "m5-2", role: "agent", content: "The Waikiki Beachfront Condo is directly across the street—2-minute walk to the sand! You'll also have a direct ocean view from your lanai.", timestamp: "2026-03-15T11:01:00Z" },
      { id: "m5-3", role: "guest", content: "Perfect! Is there a washer/dryer in the unit? We have a 5-night stay.", timestamp: "2026-03-15T11:30:00Z" },
      { id: "m5-4", role: "agent", content: "Yes! Full-size washer/dryer in the unit. Detergent pods are stocked under the bathroom sink.", timestamp: "2026-03-15T11:31:00Z" },
      { id: "m5-5", role: "guest", content: "Just checked in. Everything is spotless and the view is incredible. Very happy guests here!", timestamp: "2026-03-16T15:45:00Z" },
      { id: "m5-6", role: "agent", content: "Wonderful! Enjoy your stay, Michael. Sunsets from that lanai are truly special 🌅 Let me know if you need anything!", timestamp: "2026-03-16T15:46:00Z" },
    ],
  },
  {
    id: "conv-6",
    bookingId: "bk-5",
    guestName: "Lisa Nakamura",
    guestAvatar: "https://i.pravatar.cc/64?img=25",
    propertyId: "prop-3",
    lastMessageTime: "2026-03-10T14:00:00Z",
    unreadCount: 0,
    messages: [
      { id: "m6-1", role: "guest", content: "Hi! Our group of 6 is arriving tomorrow. Is the kitchen fully stocked with cookware?", timestamp: "2026-03-04T18:00:00Z" },
      { id: "m6-2", role: "agent", content: "Hi Lisa! Yes, fully equipped—pots, pans, cast iron, blender, coffee maker, all utensils. We also have a BBQ grill on the lanai perfect for your group!", timestamp: "2026-03-04T18:01:00Z" },
      { id: "m6-3", role: "guest", content: "The BBQ will be perfect. We just arrived—the house is even better than the photos 😍", timestamp: "2026-03-05T16:30:00Z" },
      { id: "m6-4", role: "agent", content: "So happy to hear that! Kailua Beach is steps away. Snorkel gear is in the garage closet—feel free to use it!", timestamp: "2026-03-05T16:31:00Z" },
      { id: "m6-5", role: "guest", content: "We're going through towels fast with 6 people and beach days. Any chance of fresh ones?", timestamp: "2026-03-07T10:00:00Z" },
      { id: "m6-6", role: "agent", content: "Of course! I've arranged fresh towels for today between 2–4pm—12 bath towels and 8 beach towels. No need to be present.", timestamp: "2026-03-07T10:01:00Z" },
      { id: "m6-7", role: "guest", content: "You're incredible, thank you! Best AI host we've ever had 😂", timestamp: "2026-03-07T14:30:00Z" },
      { id: "m6-8", role: "agent", content: "Ha! Happy to help 🤖 Reminder: checkout is March 12th by 11am. Hope the rest of your stay is amazing!", timestamp: "2026-03-07T14:31:00Z" },
      { id: "m6-9", role: "guest", content: "This has been the best vacation we've ever taken. We'll absolutely be back!", timestamp: "2026-03-10T14:00:00Z" },
    ],
  },
];

export function getPropertyById(id: string): Property | undefined {
  return properties.find((p) => p.id === id);
}

export function generatePropertySetup(
  address: string,
  lat: number,
  lng: number
): PropertySetupResult {
  return {
    address,
    displayName: address.split(",")[0],
    location: { lat, lng },
    zillowData: {
      estimatedValue: 1_250_000,
      bedrooms: 2,
      bathrooms: 2,
      sqft: 985,
      yearBuilt: 2018,
      propertyType: "Condo",
      suggestedNightlyRate: 289,
      projectedAnnualRevenue: 84_000,
      occupancyEstimate: 79,
    },
    comparables: [
      {
        id: "comp-1",
        name: "Waikiki Ocean View Suite",
        nightlyRate: 220,
        occupancy: 81,
        source: "airbnb",
        distanceMiles: 0.2,
        rating: 4.7,
        reviewCount: 143,
      },
      {
        id: "comp-2",
        name: "Beachside Retreat 2BR",
        nightlyRate: 265,
        occupancy: 77,
        source: "vrbo",
        distanceMiles: 0.5,
        rating: 4.8,
        reviewCount: 89,
      },
      {
        id: "comp-3",
        name: "Luxury Lanai Condo",
        nightlyRate: 320,
        occupancy: 73,
        source: "airbnb",
        distanceMiles: 0.8,
        rating: 4.9,
        reviewCount: 212,
      },
    ],
    attractions: [
      { name: "Waikiki Beach", category: "beach", distanceMiles: 0.1, rating: 4.9 },
      { name: "Duke's Waikiki Restaurant", category: "restaurant", distanceMiles: 0.3, rating: 4.6 },
      { name: "Waikiki Surf Lessons", category: "activity", distanceMiles: 0.2, rating: 4.8 },
      { name: "International Market Place", category: "shopping", distanceMiles: 0.5, rating: 4.4 },
      { name: "Diamond Head State Monument", category: "landmark", distanceMiles: 2.1, rating: 4.9 },
    ],
    cleaningServices: [
      {
        id: "clean-1",
        name: "Aloha Clean",
        pricePerTurnover: 145,
        rating: 4.5,
        reviewCount: 78,
        turnaroundHours: 3,
        badge: "Budget",
      },
      {
        id: "clean-2",
        name: "Island Sparkle",
        pricePerTurnover: 175,
        rating: 4.8,
        reviewCount: 156,
        turnaroundHours: 2,
        badge: "Recommended",
      },
      {
        id: "clean-3",
        name: "Elite Turnover",
        pricePerTurnover: 220,
        rating: 4.9,
        reviewCount: 94,
        turnaroundHours: 1.5,
        badge: "Premium",
      },
    ],
    quickbooks: {
      status: "connected",
      companyName: "New Property LLC",
      accountsLinked: 3,
      lastSync: "just now",
    },
  };
}

export function getBookingsForProperty(propertyId: string): Booking[] {
  return bookings.filter((b) => b.propertyId === propertyId);
}

export function getActionsForProperty(propertyId: string): AIAction[] {
  return aiActions.filter((a) => a.propertyId === propertyId);
}
